import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";


import CustomLayout from "@/src/components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CustomLayout>{children}</CustomLayout>
    </html>
  );
}
